# Generated by Django 3.2.13 on 2023-12-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20231215_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='RoomId',
            field=models.CharField(default='tt', max_length=1000),
            preserve_default=False,
        ),
    ]
