# Generated by Django 3.2.13 on 2023-12-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_roomid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
